"use client";

import { useState } from "react";

type Summary = { responseCount: number; consentRate: number; completionRate: number; usageDistribution: Record<string, number>; scores: Record<string, number> };
const scoreLabels: Record<string, string> = { aiDependency: "Average AI dependency", independentCapability: "Average independent capability", verification: "Average verification", aiLiteracy: "Average AI literacy", independentConfidence: "Average independent-work confidence" };

export default function ResearcherPage() {
  const [token, setToken] = useState("");
  const [summary, setSummary] = useState<Summary | null>(null);
  const [error, setError] = useState("");
  async function loadDashboard() { setError(""); const response = await fetch("/api/researcher", { headers: { "x-researcher-token": token } }); const result = await response.json(); if (!response.ok) { setError(result.error ?? "Unable to load the dashboard."); return; } setSummary(result); }
  async function downloadExport(format: "csv" | "xlsx") { const response = await fetch(`/api/researcher?format=${format}`, { headers: { "x-researcher-token": token } }); if (!response.ok) { setError(`Unable to export the ${format === "xlsx" ? "Excel workbook" : "responses"}.`); return; } const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `survey-responses.${format}`; link.click(); URL.revokeObjectURL(url); }
  if (!summary) return <main className="researcher-shell"><section className="researcher-login"><p className="research-label">Researcher dashboard</p><h1>Survey overview</h1><p>Enter the dashboard token configured for this pilot study. Participant responses are not shown on the login screen.</p><label>Researcher token<input type="password" value={token} onChange={(event) => setToken(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") loadDashboard(); }} /></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary-button" onClick={loadDashboard}>Open dashboard <span>→</span></button></section></main>;
  const maxUsage = Math.max(...Object.values(summary.usageDistribution), 1);
  return <main className="researcher-shell"><div className="researcher-wrap"><header className="researcher-header"><div><p className="research-label">Researcher dashboard</p><h1>Survey overview</h1><p>Aggregate pilot-study results and candidate research variables. These are not clinically or scientifically validated diagnostic scores.</p></div><div className="export-actions"><button className="primary-button" onClick={() => downloadExport("xlsx")}>Export Excel <span>↓</span></button><button className="secondary-button" onClick={() => downloadExport("csv")}>Export CSV <span>↓</span></button></div></header><div className="metric-grid"><Metric label="Responses" value={summary.responseCount} /><Metric label="Consent rate" value={`${summary.consentRate}%`} /><Metric label="Completion rate" value={`${summary.completionRate}%`} /></div><div className="dashboard-grid"><section className="dashboard-panel"><p className="research-label">Generative AI use</p><h2>Usage distribution</h2><div className="usage-chart">{Object.entries(summary.usageDistribution).map(([label, count]) => <div className="usage-row" key={label}><span>{label}</span><div><i style={{ width: `${(count / maxUsage) * 100}%` }} /></div><strong>{count}</strong></div>)}</div></section><section className="dashboard-panel"><p className="research-label">Candidate scores</p><h2>Research variables</h2><div className="score-list">{Object.entries(summary.scores).map(([key, value]) => <div className="score-row" key={key}><span>{scoreLabels[key]}</span><strong>{value}</strong></div>)}</div></section></div><p className="dashboard-note">Only aggregate results are displayed. Participant names, emails, contact details, and individual scores are not collected or displayed.</p></div></main>;
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div>; }
